### ISSUE TITLE
Language support error

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/ai-cfia-ia-acia.github.io#123]
If i'm on the page `/docs/dev-rel-docs` in english (EN):

![image](https://github.com/ai-cfia/ai-cfia-ia-acia.github.io/assets/49320132/e6ff964d-aee1-4a39-ba61-1e3251673ca7)

and I change the language to French (FR): 

![image](https://github.com/ai-cfia/ai-cfia-ia-acia.github.io/assets/49320132/a1995a5e-61a1-440d-8f8b-751f69a4962a)

I encounter this error

**Comment by ClemZ31** [comment]
Hi @ThomasCardin 
If you deployed locally by doing `yarn start`, it will just deploy the english version.
You have to `yarn build` and then `npm run serve` to have access to the two versions.

English one :
![image](https://github.com/ai-cfia/ai-cfia-ia-acia.github.io/assets/61210037/6d91a51f-e55e-4ca4-916e-242260fa0a7b)

French one :
![image](https://github.com/ai-cfia/ai-cfia-ia-acia.github.io/assets/61210037/5d474a61-5878-4602-88da-1b0d2700de48)

Did you just do `yarn start` ?

**Comment by ThomasCardin** [comment]
Hi Clément, thanks for the instructions. As you can see here, we use a Dockerfile to deploy our applications with Kubernetes. In this file, you can see that there is indeed a yarn build, but no npm run serve, so we are using the nginx image to serve the static pages.

```Dockerfile
FROM node:18 AS build

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build

FROM nginx:stable

COPY --from=build /app/build /usr/share/nginx/html

# Copy nginx configuration file
# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
```

Everything works normally with npm run serve. I will add the command to a README.md.
