### ISSUE TITLE
Dockerfile doesn't generate french version of the website

### ISSUE THREAD

**Issue by ClemZ31** [ai-cfia/ai-cfia-ia-acia.github.io#141]
The PR #140 and its changes on the Dockerfile prevent to build the French version, which is no longer accessible on the last deployment. Usually, I do "yarn build" then "npm run serve" to generate locally the multilingual version.

**Comment by SonOfLope** [comment]
@ClemZ31 I've noticed this thanks for reporting it. I'm debugging it since a simple build isn't fixing it
