### ISSUE TITLE
Making the homepage banner look better on mobile

### ISSUE THREAD

**Issue by RussellJimmies** [ai-cfia/ai-cfia-ia-acia.github.io#16]

**Comment by rngadam** [comment]
@RussellJimmies why is this closed? How was it fixed? How was it tested?

**Comment by RussellJimmies** [comment]
@rngadam this was an issue from when I had just posted the skeleton of the site. The issue was that when you got to mobile screen size, it looked awful with the background image, as it was too stretched out. So when we get to that screen size, I simply rotated the background vertically and it made it look way nicer.  I fixed it the day after posting the skeleton and never closed this.

I tested using the developer tools and selecting different mobile phone resolutions.
