### ISSUE TITLE
Setup automatic deployment for public AI Lab site

### ISSUE THREAD

**Issue by vivalareda** [ai-cfia/ai-cfia-ia-acia.github.io#24]
- Create gh-pages branch
- Create workflow for build
- Create workflow for deployment

**Comment by vivalareda** [comment]
https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions

**Comment by rngadam** [comment]
@redat97 

1) the title should be "Setup automatic deployment for public AI Lab site" include what it is so it's easier to understand what the issue is about in the Github Projects
2) Put this on the the Github Projects DevOps

I've mentioned this before.
