### ISSUE TITLE
Copyrights

### ISSUE THREAD

**Issue by nmeraihi** [ai-cfia/ai-cfia-ia-acia.github.io#30]
I'm not sure of using `Copyright © 2023 A.I. Lab.`

**Comment by RussellJimmies** [comment]
I removed the Copyright mention, left "2023 AI Lab" in this [PR](https://github.com/ai-cfia/ai-cfia-ia-acia.github.io/pull/38/commits/02dff52a7cf5d03887fef112650fb2d5b8036d19)
