### ISSUE TITLE
Add article to blog + document procedure on how to do so

### ISSUE THREAD

**Issue by RussellJimmies** [ai-cfia/ai-cfia-ia-acia.github.io#45]
- [ ] Add article to blog section
- [ ] Document procedure to create blog posts in readme

**Comment by leejaeka** [comment]
Attaching article in markdown format that explains brief history of text embedding and why now is a good time to use it. [text_embedding_history_article.md](https://github.com/ai-cfia/ai-cfia-ia-acia.github.io/files/13246504/text_embedding_history_article.md)
