### ISSUE TITLE
Add team introduction 

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/ai-cfia-ia-acia.github.io#48]
https://github.com/ai-cfia/dev-rel-docs/pull/69#pullrequestreview-1720400525

**Comment by rngadam** [comment]
@ThomasCardin next time use "Reference in new issue" which creates a nice quoted text block:

![image](https://github.com/ai-cfia/ai-cfia-ia-acia.github.io/assets/538542/4fe3962d-0d86-4401-b79d-7d547470a0eb)
