### ISSUE TITLE
Implement the ability to support multiple URLs for different development environment 

### ISSUE THREAD

**Issue by vivalareda** [ai-cfia/ai-cfia-ia-acia.github.io#51]
> @rngadam I don't understand the question, I deployed it and the website was accessible, it wasn't at first when I configured it wrong. I deployed it not just built it

that was the answer to the question I was asking.

Question: did you deploy at the same URL or at a different URL? we should have the ability to support dev, stage, prod.

_Originally posted by @rngadam in https://github.com/ai-cfia/ai-cfia-ia-acia.github.io/issues/50#issuecomment-1815359364_

As pointed out in this conversation, we don't have the ability to have a different URL for deployment test. It's necessary to have this so that we can test our deployment and changes while still having an operational website

**Comment by rngadam** [comment]
apparently it's a popular feature that's been requested many times but not yet implemented by Github:

https://github.com/orgs/community/discussions/47867
