### ISSUE TITLE
[introduction samuel pelletier-evraire]

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/ai-cfia-ia-acia.github.io#73]

**Comment by rngadam** [comment]
@SamuelPelletierEvraire let's talk about this issue in person, would like to know the instructions that were followed to create it.

**Comment by rngadam** [comment]
@SamuelPelletierEvraire better to explain why issues are closed or maked completed.

In this case, I believe it is because this duplicates issue #72
